name: administrasi_peserta
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.9.0
  sqflite_common_ffi_web: ^0.4.0
  cupertino_icons: ^1.0.2
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.1

  # Library Excel & Share
  excel: ^4.0.2
  path_provider: ^2.1.2
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  # 1. TAMBAHKAN LIBRARY LOGO DI SINI
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  # 2. DAFTARKAN ASSETS DI SINI (LANGKAH NO 3)
  assets:
    - assets/images/logo.png

# 3. TAMBAHKAN KONFIGURASI LOGO DI PALING BAWAH (SEJAJAR DENGAN NAME:)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
flutter_native_splash:
  color: "#FFFFFF" # Warna latar belakang (Putih). Bisa diganti misal "#3F51B5" untuk Biru
  image: assets/images/logo.png # Logo yang akan muncul di tengah layar
  android: true
  ios: true
  fullscreen: true